# Pandas 
data analysis toolkit

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

pandas can import excel,sql,csv,json,xml,pdf

## Pandas has its own data structure

## pandas -> data structure
1. Series .... 1D array
2. DataFrame .... 2D array....table
3. Panel  ....... 3D array

#### 7 >> zero dimensional >> scaler

#### 1D >> list >> 1D array >> vector >> columns >> series

#### 2D >> list in list >> 2D array >> table >> dataframe>> which contains rows and columns

#### 3D >> list in list >> 3D array >> panel

# Series : One dimesional labelled array and label is called as index.

1. container
2. homogenous
3. support for indexing
4. slicing
5. mutable
6. iterations
7. arithemtic operations
8. stats operations
9. anaytics operations

In [1]:
import pandas as pd

In [2]:
# how to create series
# using 1D array, list

In [3]:
# using list
s1=pd.Series([11,22,33,44,55])
s1

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [4]:
s1.shape

(5,)

In [5]:
# by using 1D array
import numpy as np
a=np.array([11,22,33,44,55])

In [6]:
s2=pd.Series(a)
s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

# Numpy and pandas has their own datatypes
1. integer >> 'int16' 'int32' 'int64' 'int128'
2. float >> 'float16' 'float32' 'float64' 'float128'
3. strings >> charcter, U , object

#### BY DEFAULT >> int64 , float64

# attributes and methods

In [7]:
s1=pd.Series([11,22,33,44,55],index=range(1,6))
s1

1    11
2    22
3    33
4    44
5    55
dtype: int64

In [8]:
s1=pd.Series([11,22,33,44,55,66,77,88,99,100])
s1

0     11
1     22
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9    100
dtype: int64

In [9]:
s1.shape

(10,)

In [10]:
s1.index

RangeIndex(start=0, stop=10, step=1)

In [11]:
s1.values

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100])

In [12]:
s1.dtype

dtype('int64')

In [13]:
s1.head()   # top 5 values

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [14]:
s1.tail()   # bottom 5 values

5     66
6     77
7     88
8     99
9    100
dtype: int64

In [15]:
# iteration

In [16]:
for i in s1:
    print(i)

11
22
33
44
55
66
77
88
99
100

In [17]:
# indexing

In [18]:
s1[0]

np.int64(11)

In [19]:
s1[4]

np.int64(55)

In [20]:
# s1[-2]  cannot do negative indixng

In [21]:
# slicing

In [22]:
s1[0:5]

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [23]:
s1[::-1]

9    100
8     99
7     88
6     77
5     66
4     55
3     44
2     33
1     22
0     11
dtype: int64

In [24]:
# mutable : can update elementes using indexing

In [25]:
s1[0]=99
s1

0     99
1     22
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9    100
dtype: int64

In [26]:
del s1[1]
s1

0     99
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9    100
dtype: int64

In [27]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([5,6,7,8])

In [28]:
s1+s2  # sequencial addition is done

0     6
1     8
2    10
3    12
dtype: int64

In [29]:
# broadcasting : 

s1+5

0    6
1    7
2    8
3    9
dtype: int64

In [30]:
s1/2

0    0.5
1    1.0
2    1.5
3    2.0
dtype: float64

In [31]:
# stats opertioans

In [32]:
s1=pd.Series([11,22,33,44,55,66,77,88,99,100])

In [33]:
s1.sum()

np.int64(595)

In [34]:
s1.mean()

np.float64(59.5)

In [35]:
s1.max()

100

In [36]:
s1.median()

60.5

In [37]:
s1.min()

11

In [38]:
s1.var()

1009.1666666666666

In [39]:
s1.std()

31.76738369250239

In [40]:
s1.quantile(0.25)

np.float64(35.75)

In [41]:
s1.quantile(0.75)

np.float64(85.25)

In [42]:
s1.unique()

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100])

In [43]:
s1.describe()   # describe data in a series

count     10.000000
mean      59.500000
std       31.767384
min       11.000000
25%       35.750000
50%       60.500000
75%       85.250000
max      100.000000
dtype: float64

In [44]:
s1.count()

np.int64(10)

In [45]:
s1.skew()

np.float64(-0.1403680181377665)

In [46]:
s2=pd.Series(['M','M','F','M','F'])
s2

0    M
1    M
2    F
3    M
4    F
dtype: object

In [47]:
s2.mode()

0    M
dtype: object

In [48]:
s2.value_counts()

M    3
F    2
Name: count, dtype: int64

In [49]:
# Analaytical Opertions

## DataFrame : Pandas DataFrame is a two-dimensional, size-mutable, and tabular data structure with labeled axes (rows and columns).

2D array

columns are series/ homogenuous

### how to create dataframe 
1. dictionary
2. 2D array

In [50]:
import pandas as pd

In [51]:
d1={'id':[1,2,3],
    'name':['avi','raj','sana'],
    'marks':[45,56,89]}
d1

{'id': [1, 2, 3], 'name': ['avi', 'raj', 'sana'], 'marks': [45, 56, 89]}

In [52]:
df=pd.DataFrame(d1)

In [53]:
df

   id  name  marks
0   1   avi     45
1   2   raj     56
2   3  sana     89

In [54]:
# Data frame by using 2D array

In [55]:
import pandas as pd
import numpy as np

In [56]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [57]:
df=pd.DataFrame(a,columns=['x','y','z'])
df

   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9

### DataFrame :
1. 2D array
2. tabular data structure which contain rows and columns
3. columns are series/homogenous
4. csv ,excel,sql >> import >> as a dataframe


#### **data frame values must be written in a list**

In [58]:
import pandas as pd
import numpy as np

In [59]:
# 1.  data frame by using dictionary

d1={'roll':[11,12,13],
     'name':['avi','sid','sanu'],
     'marks':[45.78, 67.31, 98.02]
   }

df=pd.DataFrame(d1)
df


# columns >> name
# rows >> numbers >> index

   roll  name  marks
0    11   avi  45.78
1    12   sid  67.31
2    13  sanu  98.02

In [60]:
# 2.  data frame using 2D array

s=np.array([[2,3,4],
          [8,5,6],
          [7,8,9]
         ])

In [61]:
s.shape

(3, 3)

In [62]:
df=pd.DataFrame(s,columns=['x','y','z'],index=range(101,104))   # using this parameters we can change column names and index changing also
df


## if wish to change index we can change index and column names

     x  y  z
101  2  3  4
102  8  5  6
103  7  8  9

### how to import differenct types of files in python
1. csv ->    .csv -> Comma separated values
2. tsv -> .tsv -> Tab separated values
3. excel ->   .xlsx -> Excel Workbook
4. sql ->   .sql -> structured query language
5. text ->   .txt -> used to store text documents
6. xml -> .xml -> Extensible markup language
7. json -> .json -> javascript object notation

### csv,tsv,txt  to read files
1. read_csv
2. read_excel
3. read_json
4. read_xml
5. read_sql

#### HOW TO READ FILES
1. USING path
2. Using File name

In [63]:
# 1. using path students.csv
# "C:\Users\marat\OneDrive\Desktop\Data Science with AI\Stats & Prob\data files\students.csv"

In [64]:
# using PATH
# r is compulsaryyy

import pandas as pd
a= pd.read_csv(r"C:\Users\marat\OneDrive\Desktop\Data Science with AI\Stats & Prob\data files\students.csv")
a

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [65]:
# 2. By using file name
# file name >> file should be in current directory  # jupyter,vs code, gogle collab current directory is differemt

In [66]:
import os
os.getcwd()

'C:\\Users\\marat\\OneDrive\\Desktop\\Data Science with AI\\Stats & Prob'

In [67]:
# does not need to write whole path :   "../models/fusion_model.pkl"
pd.read_csv("../Stats & Prob/data files/students.csv")

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [68]:
# 2. TSV - Tab Separated Values

In [69]:
# Why sep="\t"? :  TSV means Tab-Separated Values.
t= pd.read_csv("../Stats & Prob/data files/r_data.tsv", sep='\t')   

# 2. way to >>>    t= pd.read_csv("../Stats & Prob/data files/r_data.tsv", delimiter='\t')      
t

                                                 Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
...                                                 ...    ...
1381                                              clean      1
1382                                               less      0
1383                                              clean      1
1384                                               less      0
1385                                              clean      1

[1386 rows x 2 columns]

In [70]:
# text file

s=pd.read_csv("../Stats & Prob/data files/new1.txt",sep='t')
s

      a,b,c
0  11,22,33
1  44,55,66

In [71]:
# excel file 1.)

s=pd.read_excel("../Stats & Prob/data files/Sales_data.xlsx")
s

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Maharaja store,Rajesh,Heater,134,850,113900,20502.00,134402.00
1,2,2019-04-02,Maharaja store,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Neuro Enterprises,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Maharaja store,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Maharaja store,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Maharaja store,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [72]:
# 2.)
s=pd.read_excel("../Stats & Prob/data files/Sales_join.xlsx")
s

      Customer ID           State     Product Order Date   Cost  Price
0            3405         Arizona  Paperclips 2017-05-29   2.15   2.79
1            3651        Virginia      Pencil 2016-02-28   4.46   5.65
2            7687         Arizona     Notepad 2016-04-22   1.19   1.59
3            1904          Nevada         Pen 2017-08-31   4.79   5.95
4            6500         Alabama      Eraser 2017-03-01   3.04   3.75
...           ...             ...         ...        ...    ...    ...
1141         3198  North Carolina        Lamp 2017-02-12  16.92  29.95
1142         8060          Nevada      Pencil 2017-02-09   4.46   5.65
1143         6500         Alabama         Pen 2017-01-08   4.79   5.95
1144         8060          Nevada    Notebook 2016-09-23   1.76   2.35
1145         1111          Nevada    Notebook 2016-09-23   1.76   2.35

[1146 rows x 6 columns]

In [73]:
# 3.)
s=pd.read_excel("../Stats & Prob/data files/Orders.xlsx")
s

,Customer ID,Order ID,Product,Units Sold,Date,Name of customer,total revenue,total cost,total profit
0,3,266868,Chocolate Chip,292.0,2020-02-01,ACME Bites,1460.0,584.00,876.00
1,3,140794,Chocolate Chip,974.0,2020-02-01,ACME Bites,4870.0,1948.00,2922.00
2,3,684759,Chocolate Chip,2518.0,2020-06-01,ACME Bites,12590.0,5036.00,7554.00
3,4,640447,Chocolate Chip,1006.0,2020-06-01,Wholesome Foods,5030.0,2012.00,3018.00
4,2,898637,Chocolate Chip,367.0,2020-07-01,ABC Groceries,1835.0,734.00,1101.00
...,...,...,...,...,...,...,...,...,...
695,3,853295,White Chocolate Macadamia Nut,2826.0,2020-05-01,ACME Bites,16956.0,7771.50,9184.50
696,2,253981,White Chocolate Macadamia Nut,663.0,2020-09-01,ABC Groceries,3978.0,1823.25,2154.75
697,4,208456,White Chocolate Macadamia Nut,2574.0,2019-11-01,Wholesome Foods,15444.0,7078.50,8365.50
698,4,727940,White Chocolate Macadamia Nut,2438.0,2019-12-01,Wholesome Foods,14628.0,6704.50,7923.50
699,4,414628,White Chocolate Macadamia Nut,914.0,2020-12-01,Wholesome Foods,5484.0,2513.50,2970.50

## Excel files has many sheets but, read_excel by default reads 1st EXCEL sheet
### to fetch sheet_name=2

In [74]:
df1=pd.read_excel("../Stats & Prob/data files/Sales_join.xlsx",sheet_name=0)
df1

      Customer ID           State     Product Order Date   Cost  Price
0            3405         Arizona  Paperclips 2017-05-29   2.15   2.79
1            3651        Virginia      Pencil 2016-02-28   4.46   5.65
2            7687         Arizona     Notepad 2016-04-22   1.19   1.59
3            1904          Nevada         Pen 2017-08-31   4.79   5.95
4            6500         Alabama      Eraser 2017-03-01   3.04   3.75
...           ...             ...         ...        ...    ...    ...
1141         3198  North Carolina        Lamp 2017-02-12  16.92  29.95
1142         8060          Nevada      Pencil 2017-02-09   4.46   5.65
1143         6500         Alabama         Pen 2017-01-08   4.79   5.95
1144         8060          Nevada    Notebook 2016-09-23   1.76   2.35
1145         1111          Nevada    Notebook 2016-09-23   1.76   2.35

[1146 rows x 6 columns]

In [75]:
df2=pd.read_excel("../Stats & Prob/data files/Sales_join.xlsx",sheet_name=1)
df2

    Customer ID              Name  Gender
0          9562       Ryan Murphy    Male
1          3423      Rachel White  Female
2          3405     Wendall Smith    Male
3          9616       Glen Thomas    Male
4          8060      Reilly Lewis    Male
5          6500       Doug Howard    Male
6          7651    Antonio Morgan    Male
7          1498        Max Powers    Male
8          3922  Patrice Anderson  Female
9          2210     Gerry Mullner    Male
10         3880    John Singleton    Male
11         4282    Collin Stewart    Male
12         1904    Isaac Goldberg    Male
13         3198  Bridget Williams  Female
14         3651    Clarke Stevens    Male
15         7040     Allan Grayson    Male
16         7687       Maria Arden  Female
17         1111                rr    Male

In [76]:
# XML file

pd.read_xml("../Stats & Prob/data files/data.xml")

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
2,bk103,"Corets, Eva",Maeve Ascendant,Fantasy,5.95,2000-11-17,After the collapse of a nanotechnology \n ...
3,bk104,"Corets, Eva",Oberon's Legacy,Fantasy,5.95,2001-03-10,"In post-apocalypse England, the mysterious \n ..."
4,bk105,"Corets, Eva",The Sundered Grail,Fantasy,5.95,2001-09-10,"The two daughters of Maeve, half-sisters, \n ..."
5,bk106,"Randall, Cynthia",Lover Birds,Romance,4.95,2000-09-02,When Carla meets Paul at an ornithology \n ...
6,bk107,"Thurman, Paula",Splish Splash,Romance,4.95,2000-11-02,A deep sea diver finds true love twenty \n ...
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
8,bk109,"Kress, Peter",Paradox Lost,Science Fiction,6.95,2000-11-02,After an inadvertant trip through a Heisenberg...
9,bk110,"O'Brien, Tim",Microsoft .NET: The Programming Bible,Computer,36.95,2000-12-09,Microsoft's .NET initiative is explored in \n ...
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [77]:
# json File


## What does lines=True mean?
# lines=True tells Pandas that the JSON file is in JSON Lines (JSONL) format, where each line contains one separate JSON object.


import pandas as pd
a=pd.read_json("../Stats & Prob/data files/Cell_Phones_and_Accessories_5.json",lines=True)
a

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014"
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014"
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014"
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013"
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013"
...,...,...,...,...,...,...,...,...,...
194434,A1YMNTFLNDYQ1F,B00LORXVUE,eyeused2loveher,"[0, 0]",Works great just like my original one. I reall...,5,This works just perfect!,1405900800,"07 21, 2014"
194435,A15TX8B2L8B20S,B00LORXVUE,Jon Davidson,"[0, 0]",Great product. Great packaging. High quality a...,5,Great replacement cable. Apple certified,1405900800,"07 21, 2014"
194436,A3JI7QRZO1QG8X,B00LORXVUE,Joyce M. Davidson,"[0, 0]","This is a great cable, just as good as the mor...",5,Real quality,1405900800,"07 21, 2014"
194437,A1NHB2VC68YQNM,B00LORXVUE,Nurse Farrugia,"[0, 0]",I really like it becasue it works well with my...,5,I really like it becasue it works well with my...,1405814400,"07 20, 2014"
194438,A1AG6U022WHXBF,B00LORXVUE,Trisha Crocker,"[0, 0]","product as described, I have wasted a lot of m...",5,I have wasted a lot of money on cords,1405900800,"07 21, 2014"

In [78]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\marat\anaconda3\lib\site-packages (1.2.0)

WARNING: Ignoring invalid distribution ~ymongo (C:\Users\marat\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ymongo (C:\Users\marat\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ymongo (C:\Users\marat\anaconda3\Lib\site-packages)

In [79]:
import pymysql
conn=pymysql.connect(user='root',password='sidd@2004',host='localhost',database='sports_league')

In [80]:
pd.read_sql('select * from games',conn)

C:\Users\marat\AppData\Local\Temp\ipykernel_1032\1273534393.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select * from games',conn)

    game_id  team1_id  team2_id  score_team1  score_team2   game_date
0         1         1         2            5            3  2024-11-10
1         2         3         4            2            4  2024-11-11
2         3         5         6            6            6  2024-11-12
3         4         7         8            3            3  2024-11-13
4         5         9        10            7            1  2024-11-14
5         6         1         3            4            2  2024-11-15
6         7         2         4            5            5  2024-11-16
7         8         6         7            6            2  2024-11-17
8         9         8         9            4            6  2024-11-18
9        10         5        10            7            3  2024-11-19
10       11        11        12            3            5  2024-11-20
11       12        13        14            4            4  2024-11-21
12       13        15        16            7            6  2024-11-22
13       14        17        18            5            8  2024-11-23
14       15        19        20            9            2  2024-11-24
15       16        11        13            6            5  2024-11-25
16       17        12        14            7            4  2024-11-26
17       18        15        17            5            6  2024-11-27
18       19        16        18            8            7  2024-11-28
19       20        19        11            4            3  2024-11-29
20       21         3         4            7            9  2026-08-16

In [81]:
import pymysql
conn=pymysql.connect(user='root',password='sidd@2004',host='localhost',database='world')
df=pd.read_sql('select * from country',conn)
df

C:\Users\marat\AppData\Local\Temp\ipykernel_1032\1024113366.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql('select * from country',conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

# Attributes and Methods

In [82]:
df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [83]:
df.shape

(500, 10)

In [84]:
df.size

5000

In [85]:
df.columns

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [86]:
df.keys()

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [87]:
s1=df.dtypes
s1

Bill No.               int64
Date          datetime64[ns]
Party Name            object
Sales Man             object
Item Name             object
Qty                    int64
Rate                   int64
Amount                 int64
GST                  float64
Total                float64
dtype: object

In [88]:
s1.index

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [89]:
df.values

array([[1, Timestamp('2019-04-01 00:00:00'), 'Bgs Enterprises', ..., 850,
        153.0, 1003.0],
       [2, Timestamp('2019-04-02 00:00:00'), 'Bgs Enterprises', ...,
        264750, 47655.0, 312405.0],
       [3, Timestamp('2019-04-03 00:00:00'), 'Ambey Agency', ...,
        7080000, 1274400.0, 8354400.0],
       ...,
       [498, Timestamp('2020-08-10 00:00:00'), 'Rama Agency', ..., 37584,
        6765.12, 44349.12],
       [499, Timestamp('2020-08-11 00:00:00'), 'Bgs Enterprises', ...,
        46600, 8388.0, 54988.0],
       [500, Timestamp('2020-08-12 00:00:00'), 'Aruna & Co.', ...,
        2500000, 450000.0, 2950000.0]], dtype=object)

In [90]:
df.head()   # by default top 5 values

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64

In [91]:
df.tail()   # by default last 5 values

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

# Opertions on DataFrame :
1. indexing
2. slicing
3. arthimatic and mutable
4. stats
5. analytics operations

# 1. Indexing

In [92]:
df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df.head()

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64

In [93]:
df['Sales Man']  # this is a series

0      Rajesh
1       Manoj
2       Karan
3        Ajay
4      Ramesh
        ...
495    Ramesh
496    Pramod
497    Rajesh
498    Ramesh
499      Ajay
Name: Sales Man, Length: 500, dtype: object

In [94]:
df[['Sales Man']]  # added list so it comes in dataframe format

    Sales Man
0      Rajesh
1       Manoj
2       Karan
3        Ajay
4      Ramesh
..        ...
495    Ramesh
496    Pramod
497    Rajesh
498    Ramesh
499      Ajay

[500 rows x 1 columns]

In [95]:
df.columns

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [96]:
df[['Bill No.','Party Name','Item Name']]

     Bill No.        Party Name  Item Name
0           1   Bgs Enterprises     Heater
1           2   Bgs Enterprises      Apron
2           3      Ambey Agency  Gas Stove
3           4   Bgs Enterprises    Lighter
4           5  Rama Enterprises  Hose Pipe
..        ...               ...        ...
495       496   Bgs Enterprises      Apron
496       497   Manoj & Company     Heater
497       498       Rama Agency  Hose Pipe
498       499   Bgs Enterprises    Lighter
499       500       Aruna & Co.     Heater

[500 rows x 3 columns]

# 2. Slicing
1. loc >> Label based Slicing
2. iloc >> integer-position based slicing
3. boolean slicing / conditional slicing

In [97]:
# loc slicing : Label Slicing


df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [98]:
df.head()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75

In [99]:
df.tail()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [100]:
# syntax: df.loc[row_slicing, column_slicing]

df.loc[0:4,'Student ID':'Mobile Games hrs']

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs
0,1001,10,2,9,3,5
1,1002,10,6,8,2,0
2,1003,10,3,8,2,4
3,1004,11,0,10,1,5
4,1005,11,4,7,2,0

In [101]:
df.loc[4,'Class']

np.int64(11)

In [102]:
import pandas as pd
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [103]:
#  loc slicing >> LABEL slicing
# syntax: df.loc[row_slicing, column_slicing]

In [104]:
df.columns

Index(['Student ID', 'Class', 'Study hrs', 'Sleeping hrs',
       'Social Media usage hrs', 'Mobile Games hrs', 'Percantege'],
      dtype='object')

In [105]:
# rows wnats 0 to 5 and columns from class to 'Social Media usage hrs'
a= df.loc[0:5,'Class':'Social Media usage hrs']
a

   Class  Study hrs  Sleeping hrs  Social Media usage hrs
0     10          2             9                       3
1     10          6             8                       2
2     10          3             8                       2
3     11          0            10                       1
4     11          4             7                       2
5     11         10             7                       0

In [106]:
df.loc[0:5,:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96

In [107]:
# if want only 2 columns go for the list concept

df.loc[:,['Class','Percantege']]

   Class  Percantege
0     10         100
1     10          80
2     10          60
3     11          45
4     11          75
5     11          96
6     12          80
7     12          90
8     12          60
9     12          85

In [108]:
# if columns not in sequqnec the use list concept
df.loc[[0,5,9],:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
5,1006,11,10,7,0,0,96
9,1010,12,6,9,1,0,85

In [109]:
# 2.) iloc >> integer based position slicing
# df.loc[row_slicing,column_slicing]
# end index

In [110]:
df.shape

(10, 7)

In [111]:
df.iloc[0:5,0:3]

   Student ID  Class  Study hrs
0        1001     10          2
1        1002     10          6
2        1003     10          3
3        1004     11          0
4        1005     11          4

In [112]:
# all rows but 2 coloumn

df.iloc[:,0:2]

   Student ID  Class
0        1001     10
1        1002     10
2        1003     10
3        1004     11
4        1005     11
5        1006     11
6        1007     12
7        1008     12
8        1009     12
9        1010     12

In [113]:
df.iloc[[0,5,9],:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
5,1006,11,10,7,0,0,96
9,1010,12,6,9,1,0,85

In [114]:
# Boolean slicing, Conditional Slicing

df[df['Percantege']>=80]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
9,1010,12,6,9,1,0,85

In [115]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [116]:
df[(df['Class']==10) & (df['Percantege']>=90)]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100

In [117]:
df[(df['Class']==12) | (df['Percantege']>=80)]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [118]:
# ajay salesman filter that data

df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [119]:
df[df['Sales Man']=='Ajay']

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
9,10,2019-04-10,Rana Udyog,Ajay,Apron,276,904,249504,44910.72,294414.72
15,16,2019-04-16,Bgs Enterprises,Ajay,Hose Pipe,155,704,109120,19641.60,128761.60
21,22,2019-04-22,Bgs Enterprises,Ajay,Apron,322,740,238280,42890.40,281170.40
27,28,2019-04-28,Rajesh Udyog,Ajay,Gas Stove,479,938,449302,80874.36,530176.36
...,...,...,...,...,...,...,...,...,...,...
473,474,2020-07-17,Rama Enterprises,Ajay,Apron,306,559,171054,30789.72,201843.72
479,480,2020-07-23,Bhola & Co.,Ajay,Gas Stove,314,980,307720,55389.60,363109.60
485,486,2020-07-29,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00
490,491,2020-08-03,Rama Enterprises,Ajay,Apron,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [120]:
df[df['Sales Man']!='Ajay']

# another method for saleman except ajay

df[~(df['Sales Man']=='Ajay')]

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
5,6,2019-04-06,Bgs Enterprises,Pramod,Apron,475,570,270750,48735.00,319485.00
...,...,...,...,...,...,...,...,...,...,...
494,495,2020-08-07,Bgs Enterprises,Rajesh,Lighter,50,932,46600,8388.00,54988.00
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00

# 3) Mutable 

1. add columns
2. delete columns
3. update columns
4.  rows delete
5.  rows add

In [146]:
import pandas as pd
import numpy as np

In [147]:
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [122]:
# 1. add columns  .. assign it
# 2. Update columns  .. assign it

In [123]:
df.shape

(10, 7)

In [124]:
df.columns

Index(['Student ID', 'Class', 'Study hrs', 'Sleeping hrs',
       'Social Media usage hrs', 'Mobile Games hrs', 'Percantege'],
      dtype='object')

In [125]:
# add single columns ..   .. assign it

In [126]:
import numpy as np
a=np.array([11,22,33,44,55,66,77,88,99,100])
a

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100])

In [127]:
# added col_1 in dataset of pivot.xlsx

df['col_1']=a
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1
0,1001,10,2,9,3,5,100,11
1,1002,10,6,8,2,0,80,22
2,1003,10,3,8,2,4,60,33
3,1004,11,0,10,1,5,45,44
4,1005,11,4,7,2,0,75,55
5,1006,11,10,7,0,0,96,66
6,1007,12,4,6,0,0,80,77
7,1008,12,10,6,2,0,90,88
8,1009,12,2,8,2,4,60,99
9,1010,12,6,9,1,0,85,100

In [128]:
df['col_2']=range(1,11)
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,col_2
0,1001,10,2,9,3,5,100,11,1
1,1002,10,6,8,2,0,80,22,2
2,1003,10,3,8,2,4,60,33,3
3,1004,11,0,10,1,5,45,44,4
4,1005,11,4,7,2,0,75,55,5
5,1006,11,10,7,0,0,96,66,6
6,1007,12,4,6,0,0,80,77,7
7,1008,12,10,6,2,0,90,88,8
8,1009,12,2,8,2,4,60,99,9
9,1010,12,6,9,1,0,85,100,10

In [129]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [130]:
# if collumn is not present in dataset it addes the column if presesnt it updates it 

df['col_3'] = s1
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,col_2,col_3
0,1001,10,2,9,3,5,100,11,1,1
1,1002,10,6,8,2,0,80,22,2,2
2,1003,10,3,8,2,4,60,33,3,3
3,1004,11,0,10,1,5,45,44,4,4
4,1005,11,4,7,2,0,75,55,5,5
5,1006,11,10,7,0,0,96,66,6,6
6,1007,12,4,6,0,0,80,77,7,7
7,1008,12,10,6,2,0,90,88,8,8
8,1009,12,2,8,2,4,60,99,9,9
9,1010,12,6,9,1,0,85,100,10,10

In [131]:
# HOW to add two columns at a TIME

In [132]:
x=np.arange(101,121).reshape(10,2)
x

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110],
       [111, 112],
       [113, 114],
       [115, 116],
       [117, 118],
       [119, 120]])

In [133]:
df[['col_4','col_5']]=x
# adding 2 columns give it in a list

In [134]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,col_2,col_3,col_4,col_5
0,1001,10,2,9,3,5,100,11,1,1,101,102
1,1002,10,6,8,2,0,80,22,2,2,103,104
2,1003,10,3,8,2,4,60,33,3,3,105,106
3,1004,11,0,10,1,5,45,44,4,4,107,108
4,1005,11,4,7,2,0,75,55,5,5,109,110
5,1006,11,10,7,0,0,96,66,6,6,111,112
6,1007,12,4,6,0,0,80,77,7,7,113,114
7,1008,12,10,6,2,0,90,88,8,8,115,116
8,1009,12,2,8,2,4,60,99,9,9,117,118
9,1010,12,6,9,1,0,85,100,10,10,119,120

In [135]:
# update a single column 

d=np.array([1,2,3,4,5,6,7,8,9,10])
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
df['Class']=d

In [137]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,col_2,col_3,col_4,col_5
0,1001,1,2,9,3,5,100,11,1,1,101,102
1,1002,2,6,8,2,0,80,22,2,2,103,104
2,1003,3,3,8,2,4,60,33,3,3,105,106
3,1004,4,0,10,1,5,45,44,4,4,107,108
4,1005,5,4,7,2,0,75,55,5,5,109,110
5,1006,6,10,7,0,0,96,66,6,6,111,112
6,1007,7,4,6,0,0,80,77,7,7,113,114
7,1008,8,10,6,2,0,90,88,8,8,115,116
8,1009,9,2,8,2,4,60,99,9,9,117,118
9,1010,10,6,9,1,0,85,100,10,10,119,120

In [138]:
x

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110],
       [111, 112],
       [113, 114],
       [115, 116],
       [117, 118],
       [119, 120]])

In [139]:
df[['Social Media usage hrs','Mobile Games hrs']] =  x

In [140]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,col_2,col_3,col_4,col_5
0,1001,1,2,9,101,102,100,11,1,1,101,102
1,1002,2,6,8,103,104,80,22,2,2,103,104
2,1003,3,3,8,105,106,60,33,3,3,105,106
3,1004,4,0,10,107,108,45,44,4,4,107,108
4,1005,5,4,7,109,110,75,55,5,5,109,110
5,1006,6,10,7,111,112,96,66,6,6,111,112
6,1007,7,4,6,113,114,80,77,7,7,113,114
7,1008,8,10,6,115,116,90,88,8,8,115,116
8,1009,9,2,8,117,118,60,99,9,9,117,118
9,1010,10,6,9,119,120,85,100,10,10,119,120

In [141]:
#how to delte rows and columns

In [142]:
del df['Percantege']

In [143]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,col_1,col_2,col_3,col_4,col_5
0,1001,1,2,9,101,102,11,1,1,101,102
1,1002,2,6,8,103,104,22,2,2,103,104
2,1003,3,3,8,105,106,33,3,3,105,106
3,1004,4,0,10,107,108,44,4,4,107,108
4,1005,5,4,7,109,110,55,5,5,109,110
5,1006,6,10,7,111,112,66,6,6,111,112
6,1007,7,4,6,113,114,77,7,7,113,114
7,1008,8,10,6,115,116,88,8,8,115,116
8,1009,9,2,8,117,118,99,9,9,117,118
9,1010,10,6,9,119,120,100,10,10,119,120

In [ ]:
# delete a column also drop : used to delete rows and columns 0=rows ; 1=columns

df.drop('col_1',axis=1,inplace=True)

In [150]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [149]:

df.drop(['col_2','col_3'],axis=1,inplace=True)

# # when what to drop more then 3 columns just add col names in the LISt

KeyError: "['col_2', 'col_3'] not found in axis"

In [151]:
# alternative for dropping more than 2 columns
df.drop(columns=['col_4','col_5'])

KeyError: "['col_4', 'col_5'] not found in axis"

In [152]:
# to drop ROWS
df.drop(2,axis=0)

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [154]:
df.drop([4,6,7],axis=0)  # to drop multiple rows in once go use LIST

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
5,1006,11,10,7,0,0,96
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [157]:
df.drop(index=[3,8,7],inplace=True)   # no need to write axis beacuse by dfault rows are dropped

In [158]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
9,1010,12,6,9,1,0,85

In [159]:
# ADD ROWS: 
# 1. CONCAT / APPEND

In [162]:
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [164]:
df1=pd.DataFrame({'Student ID' : [1011],
                 'Class': [12],
                 'Study Hrs' : [5],
                 'Sleeping hrs': [7],
                'Social Media usage hrs' : [4],
                  'Mobile Games hrs' : [2],
                  'Percentage' : [59]
                 })

In [165]:
df1

,Student ID,Class,Study Hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percentage
0,1011,12,5,7,4,2,59

In [166]:
final=pd.concat([df,df1],axis=0,ignore_index=True)

In [167]:
final

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,Study Hrs,Percentage
0,1001,10,2.0,9,3,5,100.0,NaN,NaN
1,1002,10,6.0,8,2,0,80.0,NaN,NaN
2,1003,10,3.0,8,2,4,60.0,NaN,NaN
3,1004,11,0.0,10,1,5,45.0,NaN,NaN
4,1005,11,4.0,7,2,0,75.0,NaN,NaN
5,1006,11,10.0,7,0,0,96.0,NaN,NaN
6,1007,12,4.0,6,0,0,80.0,NaN,NaN
7,1008,12,10.0,6,2,0,90.0,NaN,NaN
8,1009,12,2.0,8,2,4,60.0,NaN,NaN
9,1010,12,6.0,9,1,0,85.0,NaN,NaN
10,1011,12,NaN,7,4,2,NaN,5.0,59.0

### ARTHIMETIC OPERATIONS

In [169]:
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [172]:
df['col_1']= df['Social Media usage hrs']+df['Mobile Games hrs']

# sequencial addition is performed!!!

In [173]:
df['col_1']

0    8
1    2
2    6
3    6
4    2
5    0
6    0
7    2
8    6
9    1
Name: col_1, dtype: int64

In [175]:
df['Percantege']= df['Percantege']+5   # broadcasting : adds value 5 in each value

In [176]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1
0,1001,10,2,9,3,5,105,8
1,1002,10,6,8,2,0,85,2
2,1003,10,3,8,2,4,65,6
3,1004,11,0,10,1,5,50,6
4,1005,11,4,7,2,0,80,2
5,1006,11,10,7,0,0,101,0
6,1007,12,4,6,0,0,85,0
7,1008,12,10,6,2,0,95,2
8,1009,12,2,8,2,4,65,6
9,1010,12,6,9,1,0,90,1

In [177]:
df['Five_percentage'] =df['Percantege'] * 5/100

In [178]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,Five_percentage
0,1001,10,2,9,3,5,105,8,5.25
1,1002,10,6,8,2,0,85,2,4.25
2,1003,10,3,8,2,4,65,6,3.25
3,1004,11,0,10,1,5,50,6,2.50
4,1005,11,4,7,2,0,80,2,4.00
5,1006,11,10,7,0,0,101,0,5.05
6,1007,12,4,6,0,0,85,0,4.25
7,1008,12,10,6,2,0,95,2,4.75
8,1009,12,2,8,2,4,65,6,3.25
9,1010,12,6,9,1,0,90,1,4.50

In [180]:
df.T  # Transpose : rows converted into columns and columns converted into ROWS

,0,1,2,3,4,5,6,7,8,9
Student ID,1001.00,1002.00,1003.00,1004.0,1005.0,1006.00,1007.00,1008.00,1009.00,1010.0
Class,10.00,10.00,10.00,11.0,11.0,11.00,12.00,12.00,12.00,12.0
Study hrs,2.00,6.00,3.00,0.0,4.0,10.00,4.00,10.00,2.00,6.0
Sleeping hrs,9.00,8.00,8.00,10.0,7.0,7.00,6.00,6.00,8.00,9.0
Social Media usage hrs,3.00,2.00,2.00,1.0,2.0,0.00,0.00,2.00,2.00,1.0
Mobile Games hrs,5.00,0.00,4.00,5.0,0.0,0.00,0.00,0.00,4.00,0.0
Percantege,105.00,85.00,65.00,50.0,80.0,101.00,85.00,95.00,65.00,90.0
col_1,8.00,2.00,6.00,6.0,2.0,0.00,0.00,2.00,6.00,1.0
Five_percentage,5.25,4.25,3.25,2.5,4.0,5.05,4.25,4.75,3.25,4.5

In [183]:
df.round(2)

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,Five_percentage
0,1001,10,2,9,3,5,105,8,5.25
1,1002,10,6,8,2,0,85,2,4.25
2,1003,10,3,8,2,4,65,6,3.25
3,1004,11,0,10,1,5,50,6,2.50
4,1005,11,4,7,2,0,80,2,4.00
5,1006,11,10,7,0,0,101,0,5.05
6,1007,12,4,6,0,0,85,0,4.25
7,1008,12,10,6,2,0,95,2,4.75
8,1009,12,2,8,2,4,65,6,3.25
9,1010,12,6,9,1,0,90,1,4.50

### Stats Operations

In [184]:
df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [185]:
df.shape

(500, 10)

In [186]:
df.columns

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [190]:
df.sum(numeric_only=True).round()

Bill No.       125250.0
Qty            395177.0
Rate           397851.0
Amount      229195504.0
GST          41255191.0
Total       270450695.0
dtype: float64

In [191]:
df['Total'].sum()   # sum total column

np.float64(270450694.72)

In [192]:
df.count()

Bill No.      500
Date          500
Party Name    500
Sales Man     500
Item Name     500
Qty           500
Rate          500
Amount        500
GST           500
Total         500
dtype: int64

In [193]:
df['Total'].count()

np.int64(500)

In [194]:
df.mean(numeric_only=True)  # mean of numeric columns

Bill No.       250.50000
Qty            790.35400
Rate           795.70200
Amount      458391.00800
GST          82510.38144
Total       540901.38944
dtype: float64

In [196]:
df['Total'].mean()    # mean of total column

np.float64(540901.38944)

In [198]:
df.min(numeric_only=True)  # minimum of numeric columns

Bill No.      1.0
Qty           1.0
Rate        250.0
Amount      250.0
GST          45.0
Total       295.0
dtype: float64

In [199]:
df['Total'].min()    # minimun of total column

295.0

In [200]:
df.max(numeric_only=True)  # maximum of numeric columns

Bill No.        500.0
Qty           10000.0
Rate           1500.0
Amount      7080000.0
GST         1274400.0
Total       8354400.0
dtype: float64

In [201]:
df['Total'].max()    # max of total column

8354400.0

In [202]:
df.columns

Index(['Bill No.', 'Date', 'Party Name', 'Sales Man', 'Item Name', 'Qty',
       'Rate', 'Amount', 'GST', 'Total'],
      dtype='object')

In [203]:
df['Party Name'].unique()      # Used to find all unique/different party names.

array(['Bgs Enterprises', 'Ambey Agency', 'Rama Enterprises',
       'Bhola & Co.', 'Radha Enterprises', 'Rana Udyog', 'Rajesh Udyog',
       'Manoj & Company', 'Rama Agency', 'Aruna & Co.', 'Om Traders',
       'Khanna Industries'], dtype=object)

In [206]:
df['Party Name'].mode()   # Used to find the most frequently occurring value.

0    Bgs Enterprises
Name: Party Name, dtype: object

In [207]:
df['Party Name'].value_counts()   # Very imp # Used to find how many times each party name occurs.

Party Name
Bgs Enterprises      176
Rama Agency           43
Manoj & Company       36
Rajesh Udyog          36
Rana Udyog            33
Bhola & Co.           32
Rama Enterprises      31
Radha Enterprises     26
Aruna & Co.           26
Ambey Agency          25
Om Traders            18
Khanna Industries     18
Name: count, dtype: int64

In [209]:
df.var(numeric_only=True)  # variance of numeric columns

Bill No.    2.087500e+04
Qty         3.847029e+06
Rate        7.434815e+04
Amount      7.136183e+11
GST         2.312123e+10
Total       9.936421e+11
dtype: float64

In [210]:
df['Total'].var()   # var of total column

993642052392.0535

In [211]:
df.std(numeric_only=True)   # standard deviation of numeric columns

Bill No.       144.481833
Qty           1961.384509
Rate           272.668563
Amount      844759.285705
GST         152056.671427
Total       996815.957132
dtype: float64

In [213]:
df['Total'].std()        # standard deviation of total columns

996815.9571315326

In [216]:
df.cov(numeric_only=True).round()   # coveraince of numeric columns

,Bill No.,Qty,Rate,Amount,GST,Total
Bill No.,20875.0,3.032300e+04,-1240.0,6.156724e+06,1.108210e+06,7.264934e+06
Qty,30323.0,3.847029e+06,-170837.0,1.252132e+09,2.253838e+08,1.477516e+09
Rate,-1240.0,-1.708370e+05,74348.0,3.275741e+07,5.896334e+06,3.865375e+07
Amount,6156724.0,1.252132e+09,32757413.0,7.136183e+11,1.284513e+11,8.420695e+11
GST,1108210.0,2.253838e+08,5896334.0,1.284513e+11,2.312123e+10,1.515725e+11
Total,7264934.0,1.477516e+09,38653747.0,8.420695e+11,1.515725e+11,9.936421e+11

In [218]:
df.corr(numeric_only=True)  # gives direction as well as sternegth

          Bill No.       Qty      Rate    Amount       GST     Total
Bill No.  1.000000  0.107002 -0.031485  0.050443  0.050443  0.050443
Qty       0.107002  1.000000 -0.319436  0.755709  0.755709  0.755709
Rate     -0.031485 -0.319436  1.000000  0.142214  0.142214  0.142214
Amount    0.050443  0.755709  0.142214  1.000000  1.000000  1.000000
GST       0.050443  0.755709  0.142214  1.000000  1.000000  1.000000
Total     0.050443  0.755709  0.142214  1.000000  1.000000  1.000000

In [220]:
df.quantile(0.25,numeric_only=True)

Bill No.       125.75
Qty            147.00
Rate           614.00
Amount      111031.50
GST          19985.67
Total       131017.17
Name: 0.25, dtype: float64

In [222]:
df['Total'].quantile(0.25)    # quantile 25% of total column

np.float64(131017.16999999998)

In [224]:
df.quantile(0.75,numeric_only=True)

Bill No.       375.25
Qty            416.00
Rate           932.00
Amount      307720.00
GST          55389.60
Total       363109.60
Name: 0.75, dtype: float64

In [223]:
df['Total'].quantile(0.75)

np.float64(363109.6)

In [225]:
df.skew(numeric_only=True)

Bill No.    0.000000
Qty         3.936091
Rate        0.659807
Amount      3.894357
GST         3.894357
Total       3.894357
dtype: float64

In [226]:
df['Total'].skew()

np.float64(3.8943565435638297)

In [229]:
df.median(numeric_only=True)

Bill No.       250.50
Qty            284.00
Rate           792.00
Amount      176972.00
GST          31854.96
Total       208826.96
dtype: float64

In [230]:
df['Total'].median()

208826.96

In [235]:
df.describe().round()    # gives stast daata numeric coloumns

,Bill No.,Date,Qty,Rate,Amount,GST,Total
count,500.0,500,500.0,500.0,500.0,500.0,500.0
mean,250.0,2019-12-06 12:00:00,790.0,796.0,458391.0,82510.0,540901.0
min,1.0,2019-04-01 00:00:00,1.0,250.0,250.0,45.0,295.0
25%,126.0,2019-08-03 18:00:00,147.0,614.0,111032.0,19986.0,131017.0
50%,250.0,2019-12-06 12:00:00,284.0,792.0,176972.0,31855.0,208827.0
75%,375.0,2020-04-09 06:00:00,416.0,932.0,307720.0,55390.0,363110.0
max,500.0,2020-08-12 00:00:00,10000.0,1500.0,7080000.0,1274400.0,8354400.0
std,144.0,NaN,1961.0,273.0,844759.0,152057.0,996816.0

In [236]:
df.describe(include='object')   # descirbe categoral column stats

             Party Name Sales Man  Item Name
count               500       500        500
unique               12         6          5
top     Bgs Enterprises    Rajesh  Hose Pipe
freq                176        88        104

# ANALYTICS METHODS

1. how to handle null values
2. how to handle duplicate rows and columns
3. how to change data types
4. rename columns
5. replace
6. .dt  or .str
7. nlargest/ nsmalledr
8. set index
9. sort_index / sort values / reset_index
10. apply / mop
11. join / concat
12. group_by / pivot_table

# 1. How to handle null values :
1. drop null >> dropna
2. fill null values >> fillna with mean /median/mode
    
         a.) mean,median -> for numeric column
        b.) mode -> for catgeorical column

In [5]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("../Stats & Prob/data files/marks1.csv")
df

    roll     name class  marks   age
0    1.0     anil    TE  56.77  22.0
1    2.0     amit    TE    NaN  21.0
2    3.0   aniket    BE  76.88  19.0
3    4.0  ajinkya    TE  69.66  20.0
4    5.0     asha    TE  63.28  20.0
5    6.0   ayesha    BE    NaN  20.0
6    7.0     amar    BE  65.34  19.0
7    8.0    amita    BE  68.33  23.0
8    9.0     amol    TE  56.75  20.0
9   10.0    anmol    BE    NaN  21.0
10   NaN      NaN   NaN    NaN   NaN

In [12]:
df.isnull().sum()

roll     1
name     1
class    1
marks    4
age      1
dtype: int64

In [13]:
df.isnull().sum().sum()

np.int64(8)

In [17]:
df.dropna(inplace=True,ignore_index=True)  # drop row which have null values

# index=True :  explicitly resets the row numbers (indices)

In [15]:
df.shape

(7, 5)

In [16]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64

In [18]:
# fill na
df=pd.read_csv("../Stats & Prob/data files/marks1.csv")
df

    roll     name class  marks   age
0    1.0     anil    TE  56.77  22.0
1    2.0     amit    TE    NaN  21.0
2    3.0   aniket    BE  76.88  19.0
3    4.0  ajinkya    TE  69.66  20.0
4    5.0     asha    TE  63.28  20.0
5    6.0   ayesha    BE    NaN  20.0
6    7.0     amar    BE  65.34  19.0
7    8.0    amita    BE  68.33  23.0
8    9.0     amol    TE  56.75  20.0
9   10.0    anmol    BE    NaN  21.0
10   NaN      NaN   NaN    NaN   NaN

In [19]:
df.head()

   roll     name class  marks   age
0   1.0     anil    TE  56.77  22.0
1   2.0     amit    TE    NaN  21.0
2   3.0   aniket    BE  76.88  19.0
3   4.0  ajinkya    TE  69.66  20.0
4   5.0     asha    TE  63.28  20.0

In [20]:
df.isnull().sum()

roll     1
name     1
class    1
marks    4
age      1
dtype: int64

In [23]:
d1=df['marks'].mean()

In [24]:
df.fillna({'marks':d1},inplace=True)   # full null value of marks column

In [25]:
df

    roll     name class      marks   age
0    1.0     anil    TE  56.770000  22.0
1    2.0     amit    TE  65.287143  21.0
2    3.0   aniket    BE  76.880000  19.0
3    4.0  ajinkya    TE  69.660000  20.0
4    5.0     asha    TE  63.280000  20.0
5    6.0   ayesha    BE  65.287143  20.0
6    7.0     amar    BE  65.340000  19.0
7    8.0    amita    BE  68.330000  23.0
8    9.0     amol    TE  56.750000  20.0
9   10.0    anmol    BE  65.287143  21.0
10   NaN      NaN   NaN  65.287143   NaN

In [26]:
df.isnull().sum()

roll     1
name     1
class    1
marks    0
age      1
dtype: int64

In [29]:
df.fillna({'age': df['age'].median()},inplace=True)   # fill age columns null values with median

In [30]:
df.isnull().sum()

roll     1
name     1
class    1
marks    0
age      0
dtype: int64

In [37]:
df['class'].mode()  # gives series of mode so we cannot add mode in it

0    BE
1    TE
Name: class, dtype: object

In [45]:
df['class'].mode()[0]  # gives first value of mode

'BE'

In [39]:
df['class'].value_counts()

class
TE    5
BE    5
Name: count, dtype: int64

In [46]:
# fills the mode null values of 0th index i.e BE

df.fillna({'class': df['class'].mode()[0]},inplace=True)

In [47]:
df.isnull().sum()

roll     1
name     1
class    0
marks    0
age      0
dtype: int64

In [48]:
df

    roll     name class      marks   age
0    1.0     anil    TE  56.770000  22.0
1    2.0     amit    TE  65.287143  21.0
2    3.0   aniket    BE  76.880000  19.0
3    4.0  ajinkya    TE  69.660000  20.0
4    5.0     asha    TE  63.280000  20.0
5    6.0   ayesha    BE  65.287143  20.0
6    7.0     amar    BE  65.340000  19.0
7    8.0    amita    BE  68.330000  23.0
8    9.0     amol    TE  56.750000  20.0
9   10.0    anmol    BE  65.287143  21.0
10   NaN      NaN    BE  65.287143  20.0

In [49]:
df.dropna(inplace=True,ignore_index=True)

In [51]:
df

   roll     name class      marks   age
0   1.0     anil    TE  56.770000  22.0
1   2.0     amit    TE  65.287143  21.0
2   3.0   aniket    BE  76.880000  19.0
3   4.0  ajinkya    TE  69.660000  20.0
4   5.0     asha    TE  63.280000  20.0
5   6.0   ayesha    BE  65.287143  20.0
6   7.0     amar    BE  65.340000  19.0
7   8.0    amita    BE  68.330000  23.0
8   9.0     amol    TE  56.750000  20.0
9  10.0    anmol    BE  65.287143  21.0

# 2. How to handle duplicate rows and columns :

In [52]:
df=pd.read_csv("../Stats & Prob/data files/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
# duplacted rows dropoing

In [54]:
df.duplicated().sum()

np.int64(1)

In [55]:
df.drop_duplicates(inplace=True,ignore_index=True)

In [56]:
df.duplicated().sum()

np.int64(0)

In [64]:
# columns

# duplicated () is for rows so to check for columns first T the df 
# then check duplcated then drop it and then AGAIN T the df

In [62]:
df.T.drop_duplicated()   # Transpose rows into columns then drop duplicated

AttributeError: 'DataFrame' object has no attribute 'drop_duplicated'

In [63]:
df.T.drop_duplicates().T

    sepal_length sepal_width petal_length petal_width    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
144          6.7         3.0          5.2         2.3  virginica
145          6.3         2.5          5.0         1.9  virginica
146          6.5         3.0          5.2         2.0  virginica
147          6.2         3.4          5.4         2.3  virginica
148          5.9         3.0          5.1         1.8  virginica

[149 rows x 5 columns]

# 3. Data Types
#### How to change Datatypes :
1. .astype() : Used to directly convert a column to a specified datatype.
2. pd.to_numeric() : Used to convert values into numeric datatype (int or float).
It is especially useful when a column may contain invalid/non-numeric values.
3. pd.to_datetime() : Used to convert values into date/time format.

In [66]:
df=pd.DataFrame({'roll':['1','2','3','4'],
                'marks':[44.56,67.23,78.55,89.12],
                 'percentage':['77.89','99.22','85.49','77.22'],
                 'date':['2024-2-2','2025-06-01','2025-04-01','2027-03-23']
                })
df

  roll  marks percentage        date
0    1  44.56      77.89    2024-2-2
1    2  67.23      99.22  2025-06-01
2    3  78.55      85.49  2025-04-01
3    4  89.12      77.22  2027-03-23

In [67]:
df.dtypes

roll           object
marks         float64
percentage     object
date           object
dtype: object

In [69]:
# 1. pd.to_datetime() : Used to convert values into date/time format.

df['date'] = pd.to_datetime(df['date'])

In [70]:
df.dtypes

roll                  object
marks                float64
percentage            object
date          datetime64[ns]
dtype: object

In [73]:
# 2. .astype() : Used to directly convert a column to a specified datatype.

df['roll']=df['roll'].astype('int64')

In [74]:
df.dtypes

roll                   int64
marks                float64
percentage            object
date          datetime64[ns]
dtype: object

In [77]:
df['percentage'] =df['percentage'].astype('float64')

In [78]:
df.dtypes

roll                   int64
marks                float64
percentage           float64
date          datetime64[ns]
dtype: object

In [79]:
# 3. pd.to_numeric() : Used to convert values into numeric datatype (int or float). It is especially useful when a column may contain invalid/non-numeric values.
df['percentage'] = pd.to_numeric(df['percentage'])

In [80]:
df.dtypes

roll                   int64
marks                float64
percentage           float64
date          datetime64[ns]
dtype: object

# 4. Rename : columns names

In [81]:
df=pd.read_csv("../Stats & Prob/data files/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [82]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [83]:
# sepal_name to s_name

df.rename({'sepal_length' : 'SL',
          'sepal_width' : 'SW'}, axis=1)

      SL   SW  petal_length  petal_width    species
0    5.1  3.5           1.4          0.2     setosa
1    4.9  3.0           1.4          0.2     setosa
2    4.7  3.2           1.3          0.2     setosa
3    4.6  3.1           1.5          0.2     setosa
4    5.0  3.6           1.4          0.2     setosa
..   ...  ...           ...          ...        ...
145  6.7  3.0           5.2          2.3  virginica
146  6.3  2.5           5.0          1.9  virginica
147  6.5  3.0           5.2          2.0  virginica
148  6.2  3.4           5.4          2.3  virginica
149  5.9  3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [86]:
# ANOTHER WAY AROUN
df.rename(columns = {'sepal_length' : 'SL',
          'sepal_width' : 'SW'}, inplace=True)

In [87]:
df

      SL   SW  petal_length  petal_width    species
0    5.1  3.5           1.4          0.2     setosa
1    4.9  3.0           1.4          0.2     setosa
2    4.7  3.2           1.3          0.2     setosa
3    4.6  3.1           1.5          0.2     setosa
4    5.0  3.6           1.4          0.2     setosa
..   ...  ...           ...          ...        ...
145  6.7  3.0           5.2          2.3  virginica
146  6.3  2.5           5.0          1.9  virginica
147  6.5  3.0           5.2          2.0  virginica
148  6.2  3.4           5.4          2.3  virginica
149  5.9  3.0           5.1          1.8  virginica

[150 rows x 5 columns]

###  ** Changing rows names not poosible we cannot chnage index name

# 5.  Replace method
1. spelling misatked in the value of an column use replace()
2. complsuary used {} when passing name of the column

In [90]:
# want to chnge names insid species columns more than one name of species use dict inside dict

df.replace({'species': {'setosa': 'ST' ,
                       'versicolor' : 'VS',
                        'virginica' : 'VG' }}, inplace=True)

In [91]:
df['species'].value_counts()

species
ST    50
VS    50
VG    50
Name: count, dtype: int64

# 6. .dt and .str

1. .dt — Date and Time Operations 📅 : The .dt accessor is used when a column has a datetime datatype.
2. .str — String Operations 🔤 : The .str accessor is used to perform operations on text/string columns.

In [92]:
df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

## Common .dt Functions are :
1. df['Date'].dt.year
2. df['Date'].dt.month
3. df['Date'].dt.day
4. df['Date'].dt.hour
5. df['Date'].dt.minute
6. df['Date'].dt.day_name()
7. df['Date'].dt.month_name()

In [93]:
df.dtypes

Bill No.               int64
Date          datetime64[ns]
Party Name            object
Sales Man             object
Item Name             object
Qty                    int64
Rate                   int64
Amount                 int64
GST                  float64
Total                float64
dtype: object

In [95]:
# to access year from df and create a column of year in a df

df['Year'] = df['Date'].dt.year

In [96]:
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total,Year
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00,2019
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00,2019
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00,2019
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44,2019
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64,2019
...,...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00,2020
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92,2020
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12,2020
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00,2020
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00,2020

In [101]:
df['Date'].dt.month

0      4
1      4
2      4
3      4
4      4
      ..
495    8
496    8
497    8
498    8
499    8
Name: Date, Length: 500, dtype: int32

In [102]:
df['Date'].dt.month_name()

0       April
1       April
2       April
3       April
4       April
        ...
495    August
496    August
497    August
498    August
499    August
Name: Date, Length: 500, dtype: object

In [104]:
df['Date'].dt.quarter

0      2
1      2
2      2
3      2
4      2
      ..
495    3
496    3
497    3
498    3
499    3
Name: Date, Length: 500, dtype: int32

In [105]:
df['Date'].dt.day

0       1
1       2
2       3
3       4
4       5
       ..
495     8
496     9
497    10
498    11
499    12
Name: Date, Length: 500, dtype: int32

In [106]:
df['Date'].dt.day_name()

0         Monday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...
495     Saturday
496       Sunday
497       Monday
498      Tuesday
499    Wednesday
Name: Date, Length: 500, dtype: object

# Common .str functions
1. df['Name'].str.upper()
2. df['Name'].str.lower()
3. df['Name'].str.title()
4. df['Name'].str.len()
5. df['Name'].str.strip()
6. df['Name'].str.contains()
7. df['Name'].str.replace()
8. df['Name'].str.startswith()
9. df['Name'].str.endswith()

In [107]:
df['Party Name'].str.upper()

0       BGS ENTERPRISES
1       BGS ENTERPRISES
2          AMBEY AGENCY
3       BGS ENTERPRISES
4      RAMA ENTERPRISES
             ...
495     BGS ENTERPRISES
496     MANOJ & COMPANY
497         RAMA AGENCY
498     BGS ENTERPRISES
499         ARUNA & CO.
Name: Party Name, Length: 500, dtype: object

In [108]:
df['Party Name'].str.strip()

0       Bgs Enterprises
1       Bgs Enterprises
2          Ambey Agency
3       Bgs Enterprises
4      Rama Enterprises
             ...
495     Bgs Enterprises
496     Manoj & Company
497         Rama Agency
498     Bgs Enterprises
499         Aruna & Co.
Name: Party Name, Length: 500, dtype: object

# 8. set index / sort_index / sort values / reset_index

1. set_index() : set_index() is used to make an existing column the index of the DataFrame.
Syntax :   df.set_index('column_name')
2. sort_index() : sort_index() is used to sort the DataFrame according to its index
3. sort_values(): sort_values() is used to sort the DataFrame according to the values in a column.
4. reset_index() : reset_index() is used to remove the existing index and bring it back as a normal column.

In [109]:
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [115]:
df.sort_index(ascending=False)  # by default is ascenidng sorting

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
9,1010,12,6,9,1,0,85
8,1009,12,2,8,2,4,60
7,1008,12,10,6,2,0,90
6,1007,12,4,6,0,0,80
5,1006,11,10,7,0,0,96
4,1005,11,4,7,2,0,75
3,1004,11,0,10,1,5,45
2,1003,10,3,8,2,4,60
1,1002,10,6,8,2,0,80
0,1001,10,2,9,3,5,100

In [117]:
df.reset_index()  # to reset index if we have sort is desceicng

,index,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,0,1001,10,2,9,3,5,100
1,1,1002,10,6,8,2,0,80
2,2,1003,10,3,8,2,4,60
3,3,1004,11,0,10,1,5,45
4,4,1005,11,4,7,2,0,75
5,5,1006,11,10,7,0,0,96
6,6,1007,12,4,6,0,0,80
7,7,1008,12,10,6,2,0,90
8,8,1009,12,2,8,2,4,60
9,9,1010,12,6,9,1,0,85

In [118]:
df.reset_index(drop=True)  #

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [119]:
df.set_index('Student ID',inplace=True)

In [120]:
df

,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Student ID,,,,,,
1001,10,2,9,3,5,100
1002,10,6,8,2,0,80
1003,10,3,8,2,4,60
1004,11,0,10,1,5,45
1005,11,4,7,2,0,75
1006,11,10,7,0,0,96
1007,12,4,6,0,0,80
1008,12,10,6,2,0,90
1009,12,2,8,2,4,60
1010,12,6,9,1,0,85

In [121]:
df.shape

(10, 6)

In [122]:
df.columns

Index(['Class', 'Study hrs', 'Sleeping hrs', 'Social Media usage hrs',
       'Mobile Games hrs', 'Percantege'],
      dtype='object')

In [126]:
df.sort_values('Percantege',ascending=False).head(3)

,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Student ID,,,,,,
1001,10,2,9,3,5,100
1006,11,10,7,0,0,96
1008,12,10,6,2,0,90

# nsmallest() and nlargest() in Pandas :
These functions are used to quickly find the smallest or largest n values from a DataFrame column.

1. nsmallest() : nsmallest() returns the n rows having the smallest values in a particular column.

Syntax
df.nsmallest(n, 'column_name')

2. nlargest() : nlargest() returns the n rows having the largest values in a particular column.

Syntax
df.nlargest(n, 'column_name')

In [128]:
df.nlargest(3,'Percantege')   # want 3 largest percantage values from a df

,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Student ID,,,,,,
1001,10,2,9,3,5,100
1006,11,10,7,0,0,96
1008,12,10,6,2,0,90

In [132]:
df.nsmallest(10,'Percantege')    # want 3 smallest percantage values from a df

,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Student ID,,,,,,
1004,11,0,10,1,5,45
1003,10,3,8,2,4,60
1009,12,2,8,2,4,60
1005,11,4,7,2,0,75
1007,12,4,6,0,0,80
1002,10,6,8,2,0,80
1010,12,6,9,1,0,85
1008,12,10,6,2,0,90
1006,11,10,7,0,0,96
1001,10,2,9,3,5,100

# apply , map,join,concat

1. join(): join multiple tables on related columns
2. concat()  : is used to combine multiple DataFrames along rows or columns.

In [142]:
import pandas as pd
import numpy as np

### a.)  join (merge) >> join multiple tables on related columns
###  left join, right join, full join , inner join

In [134]:
df1=df=pd.read_excel("../Stats & Prob/data files/sales_join.xlsx", sheet_name=0)
df2=df=pd.read_excel("../Stats & Prob/data files/sales_join.xlsx", sheet_name=1)

In [135]:
df1

      Customer ID           State     Product Order Date   Cost  Price
0            3405         Arizona  Paperclips 2017-05-29   2.15   2.79
1            3651        Virginia      Pencil 2016-02-28   4.46   5.65
2            7687         Arizona     Notepad 2016-04-22   1.19   1.59
3            1904          Nevada         Pen 2017-08-31   4.79   5.95
4            6500         Alabama      Eraser 2017-03-01   3.04   3.75
...           ...             ...         ...        ...    ...    ...
1141         3198  North Carolina        Lamp 2017-02-12  16.92  29.95
1142         8060          Nevada      Pencil 2017-02-09   4.46   5.65
1143         6500         Alabama         Pen 2017-01-08   4.79   5.95
1144         8060          Nevada    Notebook 2016-09-23   1.76   2.35
1145         1111          Nevada    Notebook 2016-09-23   1.76   2.35

[1146 rows x 6 columns]

In [136]:
df2

    Customer ID              Name  Gender
0          9562       Ryan Murphy    Male
1          3423      Rachel White  Female
2          3405     Wendall Smith    Male
3          9616       Glen Thomas    Male
4          8060      Reilly Lewis    Male
5          6500       Doug Howard    Male
6          7651    Antonio Morgan    Male
7          1498        Max Powers    Male
8          3922  Patrice Anderson  Female
9          2210     Gerry Mullner    Male
10         3880    John Singleton    Male
11         4282    Collin Stewart    Male
12         1904    Isaac Goldberg    Male
13         3198  Bridget Williams  Female
14         3651    Clarke Stevens    Male
15         7040     Allan Grayson    Male
16         7687       Maria Arden  Female
17         1111                rr    Male

In [137]:
df1.columns

Index(['Customer ID', 'State', 'Product', 'Order Date', 'Cost', 'Price'], dtype='object')

In [138]:
df2.columns

Index(['Customer ID', 'Name', 'Gender'], dtype='object')

In [139]:
pd.merge(df1,df2,how='inner',on='Customer ID')

,Customer ID,State,Product,Order Date,Cost,Price,Name,Gender
0,3405,Arizona,Paperclips,2017-05-29,2.15,2.79,Wendall Smith,Male
1,3651,Virginia,Pencil,2016-02-28,4.46,5.65,Clarke Stevens,Male
2,7687,Arizona,Notepad,2016-04-22,1.19,1.59,Maria Arden,Female
3,1904,Nevada,Pen,2017-08-31,4.79,5.95,Isaac Goldberg,Male
4,6500,Alabama,Eraser,2017-03-01,3.04,3.75,Doug Howard,Male
...,...,...,...,...,...,...,...,...
1141,3198,North Carolina,Lamp,2017-02-12,16.92,29.95,Bridget Williams,Female
1142,8060,Nevada,Pencil,2017-02-09,4.46,5.65,Reilly Lewis,Male
1143,6500,Alabama,Pen,2017-01-08,4.79,5.95,Doug Howard,Male
1144,8060,Nevada,Notebook,2016-09-23,1.76,2.35,Reilly Lewis,Male
1145,1111,Nevada,Notebook,2016-09-23,1.76,2.35,rr,Male

In [ ]:
# concat()/ append/ union

In [143]:
df1=pd.DataFrame({'f_name':['raj','avi','sam'],'s_name':['kate','kumar','Desza']})
df2=pd.DataFrame({'f_name':['sana','tanvi','rita'],'s_name':['khan','kolte','kumari']})

In [144]:
df1

  f_name s_name
0    raj   kate
1    avi  kumar
2    sam  Desza

In [145]:
df2

  f_name  s_name
0   sana    khan
1  tanvi   kolte
2   rita  kumari

In [149]:
result= pd.concat((df1,df2),ignore_index=True)   # combines like a stack
result

  f_name  s_name
0    raj    kate
1    avi   kumar
2    sam   Desza
3   sana    khan
4  tanvi   kolte
5   rita  kumari

# groupby / pivot table :

1. A pivot table is used to summarize and analyze data by arranging it according to rows, columns, and values.
2. groupby() is used to group data according to a particular column and then perform calculations such as:

        a. sum()
        b. mean()
        c. count()
        d. max()
        e. min()

In [151]:
df=pd.read_excel("../Stats & Prob/data files/pivot.xlsx")
df

,Bill No.,Date,Party Name,Sales Man,Item Name,Qty,Rate,Amount,GST,Total
0,1,2019-04-01,Bgs Enterprises,Rajesh,Heater,1,850,850,153.00,1003.00
1,2,2019-04-02,Bgs Enterprises,Manoj,Apron,353,750,264750,47655.00,312405.00
2,3,2019-04-03,Ambey Agency,Karan,Gas Stove,8000,885,7080000,1274400.00,8354400.00
3,4,2019-04-04,Bgs Enterprises,Ajay,Lighter,452,629,284308,51175.44,335483.44
4,5,2019-04-05,Rama Enterprises,Ramesh,Hose Pipe,298,826,246148,44306.64,290454.64
...,...,...,...,...,...,...,...,...,...,...
495,496,2020-08-08,Bgs Enterprises,Ramesh,Apron,50,932,46600,8388.00,54988.00
496,497,2020-08-09,Manoj & Company,Pramod,Heater,193,808,155944,28069.92,184013.92
497,498,2020-08-10,Rama Agency,Rajesh,Hose Pipe,58,648,37584,6765.12,44349.12
498,499,2020-08-11,Bgs Enterprises,Ramesh,Lighter,50,932,46600,8388.00,54988.00
499,500,2020-08-12,Aruna & Co.,Ajay,Heater,10000,250,2500000,450000.00,2950000.00

In [ ]:
# GROUP BY : 

# total sales by party name

In [154]:
r1=df.groupby(by="Party Name")['Total'].sum()

Party Name
Ambey Agency         18101192.92
Aruna & Co.          20664557.66
Bgs Enterprises      49425675.88
Bhola & Co.          10522557.96
Khanna Industries    13349734.12
Manoj & Company      39582699.98
Om Traders           27807017.42
Radha Enterprises     9134702.14
Rajesh Udyog         27897613.10
Rama Agency          15229488.28
Rama Enterprises     13022672.34
Rana Udyog           25712782.92
Name: Total, dtype: float64

In [157]:
r1.sort_values(ascending=False)

Party Name
Bgs Enterprises      49425675.88
Manoj & Company      39582699.98
Rajesh Udyog         27897613.10
Om Traders           27807017.42
Rana Udyog           25712782.92
Aruna & Co.          20664557.66
Ambey Agency         18101192.92
Rama Agency          15229488.28
Khanna Industries    13349734.12
Rama Enterprises     13022672.34
Bhola & Co.          10522557.96
Radha Enterprises     9134702.14
Name: Total, dtype: float64

In [165]:
# party wise average sales

r2=df.groupby(by='Party Name')['Total'].mean()

In [166]:
r2.round()

Party Name
Ambey Agency          724048.0
Aruna & Co.           794791.0
Bgs Enterprises       280828.0
Bhola & Co.           328830.0
Khanna Industries     741652.0
Manoj & Company      1099519.0
Om Traders           1544834.0
Radha Enterprises     351335.0
Rajesh Udyog          774934.0
Rama Agency           354174.0
Rama Enterprises      420086.0
Rana Udyog            779175.0
Name: Total, dtype: float64

In [169]:
# party wise average sales want result in dataframe add total in a LIST

r2=df.groupby(by='Party Name')[['Total']].mean()
r2

                          Total
Party Name
Ambey Agency       7.240477e+05
Aruna & Co.        7.947907e+05
Bgs Enterprises    2.808277e+05
Bhola & Co.        3.288299e+05
Khanna Industries  7.416519e+05
Manoj & Company    1.099519e+06
Om Traders         1.544834e+06
Radha Enterprises  3.513347e+05
Rajesh Udyog       7.749337e+05
Rama Agency        3.541741e+05
Rama Enterprises   4.200862e+05
Rana Udyog         7.791752e+05

### Pivot Table : 
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',

In [176]:
r4=pd.pivot_table(data=df,
               values='Total',
              index='Party Name',
                aggfunc='sum')

r4.round()

                        Total
Party Name
Ambey Agency       18101193.0
Aruna & Co.        20664558.0
Bgs Enterprises    49425676.0
Bhola & Co.        10522558.0
Khanna Industries  13349734.0
Manoj & Company    39582700.0
Om Traders         27807017.0
Radha Enterprises   9134702.0
Rajesh Udyog       27897613.0
Rama Agency        15229488.0
Rama Enterprises   13022672.0
Rana Udyog         25712783.0

In [179]:
r4.nlargest(3,'Total')

                       Total
Party Name
Bgs Enterprises  49425675.88
Manoj & Company  39582699.98
Rajesh Udyog     27897613.10

In [180]:

r4=pd.pivot_table(data=df,
               values=['Total','Qty'],
              index='Party Name',
                aggfunc='sum')

r4.round()

                     Qty       Total
Party Name
Ambey Agency       15965  18101193.0
Aruna & Co.        55809  20664558.0
Bgs Enterprises    67835  49425676.0
Bhola & Co.        10273  10522558.0
Khanna Industries  16833  13349734.0
Manoj & Company    34948  39582700.0
Om Traders         26540  27807017.0
Radha Enterprises  15915   9134702.0
Rajesh Udyog       69450  27897613.0
Rama Agency        25483  15229488.0
Rama Enterprises   12988  13022672.0
Rana Udyog         43138  25712783.0

In [183]:
# drill down goes in detail of the thing
r4=pd.pivot_table(data=df,
               values=['Total'],
              index='Party Name',
                  columns='Sales Man',
                aggfunc='sum')

r4.round()

                        Total                                                  \
Sales Man                Ajay       Karan       Manoj      Pramod      Rajesh
Party Name
Ambey Agency        1144432.0  12279040.0    543149.0    511856.0   1317638.0
Aruna & Co.        16520000.0   1868362.0    466196.0    776701.0    295500.0
Bgs Enterprises     9522613.0   8632976.0  11382430.0   6006986.0   8255189.0
Bhola & Co.         3647950.0   1082886.0   1184220.0   2292946.0   1092340.0
Khanna Industries   2018242.0   2105138.0   1824988.0   3594988.0   3405914.0
Manoj & Company     5782000.0    722389.0    263815.0   4725735.0    753194.0
Om Traders          1770000.0   3724014.0   3845527.0   7989997.0   3829360.0
Radha Enterprises   1504368.0    649873.0   6305092.0    316280.0    174444.0
Rajesh Udyog         991281.0     54988.0   4454722.0    623583.0  18490676.0
Rama Agency         3066881.0   3098905.0    288237.0    949565.0   3294697.0
Rama Enterprises    1689526.0   6165266.0   1360311.0   2135437.0   1085241.0
Rana Udyog          1824403.0   1292821.0   1911051.0  16239109.0   3782284.0


Sales Man              Ramesh
Party Name
Ambey Agency        2305078.0
Aruna & Co.          737799.0
Bgs Enterprises     5625482.0
Bhola & Co.         1222216.0
Khanna Industries    400464.0
Manoj & Company    27335567.0
Om Traders          6648120.0
Radha Enterprises    184645.0
Rajesh Udyog        3282364.0
Rama Agency         4531202.0
Rama Enterprises     586891.0
Rana Udyog           663115.0

In [196]:
# years wise sales
pd.pivot_table(
    data= df,
    values='Total',
    index=df['Date'].dt.year,
    aggfunc=['sum']
).round()

              sum
            Total
Date
2019  138561498.0
2020  131889197.0

In [197]:
# years wise sales using multiplle aggfunctsions

pd.pivot_table(
    data= df,
    values='Total',
    index=df['Date'].dt.year,
    aggfunc=['sum','mean','median']
).round()

              sum      mean    median
            Total     Total     Total
Date
2019  138561498.0  503860.0  223799.0
2020  131889197.0  586174.0  184571.0

In [203]:
# 3 items sales are high

pd.pivot_table(data=df,
              values='Total',
              index='Item Name',
               aggfunc='sum'
              ).nlargest(3,'Total')

                 Total
Item Name
Gas Stove  62936008.00
Heater     62760780.36
Apron      56530511.34

# apply / map 

1. apply() : apply() is used to apply a function to each value, row, or column.
2. map() : map() is mainly used with a Series (single column) to transform or replace values.

In [204]:
df=pd.read_csv("../Stats & Prob/data files/students.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,100
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [209]:
# apply column divide by 2

df['sq of percantege'] = df['Percantege'].apply(lambda x : x**2)
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,sq of percantege
0,1001,10,2,9,3,5,100,10000,10000
1,1002,10,6,8,2,0,80,6400,6400
2,1003,10,3,8,2,4,60,3600,3600
3,1004,11,0,10,1,5,45,2025,2025
4,1005,11,4,7,2,0,75,5625,5625
5,1006,11,10,7,0,0,96,9216,9216
6,1007,12,4,6,0,0,80,6400,6400
7,1008,12,10,6,2,0,90,8100,8100
8,1009,12,2,8,2,4,60,3600,3600
9,1010,12,6,9,1,0,85,7225,7225

In [212]:
# length of a percentage column

df['Len of %'] = df['Percantege'].apply(lambda x : len(str(x)))

In [213]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,sq of percantege,Len of %
0,1001,10,2,9,3,5,100,10000,10000,3
1,1002,10,6,8,2,0,80,6400,6400,2
2,1003,10,3,8,2,4,60,3600,3600,2
3,1004,11,0,10,1,5,45,2025,2025,2
4,1005,11,4,7,2,0,75,5625,5625,2
5,1006,11,10,7,0,0,96,9216,9216,2
6,1007,12,4,6,0,0,80,6400,6400,2
7,1008,12,10,6,2,0,90,8100,8100,2
8,1009,12,2,8,2,4,60,3600,3600,2
9,1010,12,6,9,1,0,85,7225,7225,2

In [215]:
df['Grade'] = df['Percantege'].apply(lambda x : 'Good' if x> 70 else 'Bad')

In [216]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,sq of percantege,Len of %,Grade
0,1001,10,2,9,3,5,100,10000,10000,3,Good
1,1002,10,6,8,2,0,80,6400,6400,2,Good
2,1003,10,3,8,2,4,60,3600,3600,2,Bad
3,1004,11,0,10,1,5,45,2025,2025,2,Bad
4,1005,11,4,7,2,0,75,5625,5625,2,Good
5,1006,11,10,7,0,0,96,9216,9216,2,Good
6,1007,12,4,6,0,0,80,6400,6400,2,Good
7,1008,12,10,6,2,0,90,8100,8100,2,Good
8,1009,12,2,8,2,4,60,3600,3600,2,Bad
9,1010,12,6,9,1,0,85,7225,7225,2,Good

In [220]:
# map : apply functions on column or Series 
# also used for replcaing values

In [221]:
df['Grade'] = df['Percantege'].map(lambda x : 'Good' if x> 70 else 'Bad')

In [222]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege,col_1,sq of percantege,Len of %,Grade
0,1001,10,2,9,3,5,100,10000,10000,3,Good
1,1002,10,6,8,2,0,80,6400,6400,2,Good
2,1003,10,3,8,2,4,60,3600,3600,2,Bad
3,1004,11,0,10,1,5,45,2025,2025,2,Bad
4,1005,11,4,7,2,0,75,5625,5625,2,Good
5,1006,11,10,7,0,0,96,9216,9216,2,Good
6,1007,12,4,6,0,0,80,6400,6400,2,Good
7,1008,12,10,6,2,0,90,8100,8100,2,Good
8,1009,12,2,8,2,4,60,3600,3600,2,Bad
9,1010,12,6,9,1,0,85,7225,7225,2,Good

In [223]:
df=pd.read_csv("../Stats & Prob/data files/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [227]:
df['species']=df['species'].map({'setosa' : 'ST',
                  'versicolor':'VS',
                  'virginica':'VG'})

In [228]:
df['species']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
145    NaN
146    NaN
147    NaN
148    NaN
149    NaN
Name: species, Length: 150, dtype: object